#!/usr/bin/env bash
#Bash script containing commands to automatically configure a Ubuntu machine
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '52 a   location/redirect_me {\n\t\treturn 301 www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
