#!/usr/bin/env bash
#This Bash script configures your Nginx server to have a custom 404 page
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Hello World!" > /var/www/html/index.html
virtual_server_block=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        error_page 404 /error_404.html;
        location /not_found.html {
                internal;
        }
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}
"
sudo echo "Ceci n'est pas une page" > /var/www/html/error_404.html
echo "$virtual_server_block" > /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx reload
