#!/usr/bin/env bash
#This Bash script installs my load balancer
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get update
sudo apt-get install -y haproxy=2.0.\*
sudo cp /etc/haproxy/haproxy.cfg{,.backup}
echo "ENABLED=1" >> /etc/default/haproxy
balancer=\
"backend web-backend
        balance roundrobin
        server 67118-web-01 100.25.180.87:80 check
        server 67011-web-02 18.209.225.78:80 check
frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend"
echo "$balancer" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
