#!/usr/bin/env bash
#This Bash script contains the minimum number of commands to automate my fix
sudo apt-get update
sudo apt-get -y install nginx
sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sudo service nginx start
