#!/usr/bin/env bash
#This Bash script contains the minimum number of commands to automate my fix
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo echo "" > /run/nginx.pid
sudo service nginx restart
