#!/usr/bin/env bash
#Displays numbers from 1 to 20 and:
#Displays 4 and then bad luck from China for the 4th loop iteration
#Displays 9 and then bad luck from Japan for the 9th loop iteration
#Displays 17 and then bad luck from Italy for the 17th loop iteration

n="1"
while [ $n -lt 21 ]
do
    case $n in
	4) echo $n
	    echo "bad luck from China";;
	9) echo $n
	    echo "bad luck from Japan";;
	17) echo $n
	    echo "bad luck from Italy";;
	*) echo $n
    esac
    n=$((n+1))
done
