#!/usr/bin/env bash
#Displays the content of the current directory.
#Displays in a list format.
#Displays Where only the part of the name,
#after the first dash is displayed.
for index in *
do
    echo "$index" | cut -d'-' -f2
done
