#!/usr/bin/env bash
#Displays the content of the current directory.
#Displays in a list format.
#Displays Where only the part of the name,
#after the first dash is displayed.
ls=$(ls)
for n in $ls; do
  echo "$n" | cut -d '-' -f2
done
